function showTeams() {
  document.getElementById("overview").outerHTML = "<div class='w3-container w3-light-gray' id = 'overview'><h2>Overview</h2><p>This is an online web portal for finding soccer scores pertaining to various teams. Click the icon of the team you would like to see scores from, or click the <b>League Portal</b> link above to view leagues instead of teams. The scores are powered by Google.</p></div>";
  document.getElementById("div0").outerHTML = "<div class = 'League' id = 'div0'><h2>Real Madrid</h2><a href='https://www.google.com/search?q=real+madrid&client=ubuntu&hs=KcS&channel=fs&sxsrf=APq-WBu31abMO7rnxpTkBn1G7aNnl_rXqw%3A1646941577980&ei=iVUqYtK9O42gptQPsZmBsAQ&ved=0ahUKEwiSpuK9p7z2AhUNkIkEHbFMAEYQ4dUDCA4&uact=5&oq=real+madrid&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBAgjECcyBAgjECcyCwguEIAEELEDEIMBMgsIABCABBCxAxCDATIECAAQQzIKCAAQsQMQgwEQQzIECAAQQzIECAAQQzIECAAQQzoFCAAQkQI6CAguELEDEIMBOgUILhCABDoICAAQsQMQgwE6EAguEIAEEIcCELEDEIMBEBQ6BAguEEM6DQguELEDEMcBENEDEENKBAhBGABKBAhGGABQtwVY6RFggBNoAXABeACAAaEBiAGdCZIBAzQuN5gBAKABAcABAQ&sclient=gws-wiz#sie=t;/m/06l22;2;/m/09gqx;mt;fp;1;;'><img src='https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/357px-Real_Madrid_CF.svg.png' id='Leaguelogo'></a><p id='Leaguetext'><b>Real Madrid: One of the most popular and richest Spanish clubs in the world. </b> <br>Skill Level: World Class<br> Country:  🇪🇸<br> Year Founded: 1902<br> Notable Player: Karim Benzema</p></div>";
  document.getElementById("div1").outerHTML = "<div class = 'League'id = 'div1'><h2>FC Barcelona</h2><a href='https://www.google.com/search?q=fc+barcelona&oq=fc+barcelona&aqs=chrome.0.0i131i355i433i512j0i67j0i67i433j0i67l2j69i60l3.2240j1j4&sourceid=chrome&ie=UTF-8#sie=t;/m/0hvgt;2;/m/09gqx;mt;fp;1;;'><img src='https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/142px-FC_Barcelona_%28crest%29.svg.png' id='Leaguelogo'></a><p id='Leaguetext'><b>FC Barcelona: A very popular and wealthy club, Barcelona is a symbol of Catalan culture and has a passionate fanbase. </b><br> Skill Level: High<br> Country: 🇪🇸 <br>Year Founded: 1899<br> Notable Player: Frenkie de Jong</p></div>";
  document.getElementById("div2").outerHTML = "<div class = 'League'id = 'div2'><h2>Manchester United</h2><a href='https://www.google.com/search?q=Manchester+United&oq=Manchester+United&aqs=chrome..69i57j69i59j0i271l2j69i60.504j0j4&sourceid=chrome&ie=UTF-8#sie=t;/m/050fh;2;/m/02_tc;mt;fp;1;;'><img src='https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/296px-Manchester_United_FC_crest.svg.png' id='Leaguelogo'></a><p id='Leaguetext'><b>Manchester United: One of England's most popular clubs, they attracted much attention recently after signing former Real Madrid forward Cristiano Ronaldo <br><i>(although it is spectualed that he will be leaving due to the team's poor performance)</i>. </b><br> Skill Level: High<br> Country: 🏴󠁧󠁢󠁥󠁮󠁧󠁿 <br>Year Founded: 1878<br> Notable Player: Cristiano Ronaldo</p></div>";
  document.getElementById("div3").outerHTML = "<div class = 'League'id = 'div3'><h2>LA Galaxy</h2><a href='https://www.google.com/search?q=la+galaxy&oq=la+galaxy&aqs=chrome..69i57j0i67j0i131i433i512j0i67l3j46i175i199i433i512j0i433i512j0i67.1634j1j4&sourceid=chrome&ie=UTF-8#sie=t;/m/01k2yr;2;/m/0jfpf;mt;fp;1;;'><img src='https://upload.wikimedia.org/wikipedia/commons/7/70/Los_Angeles_Galaxy_logo.svg' id='Leaguelogo'></a><p id='Leaguetext'><b>Los Angeles Galaxy: One of the most popular and valuable American clubs, the LA Galaxy made headlines in 2007 when they signed David Beckham from Real Madrid. </b><br> Skill Level: Medium<br> Country: 🇺🇸 <br>Year Founded: 1994<br> Notable Player: Efraín Álvarez</p></div>";
  document.getElementById("div4").outerHTML = "<div class = 'League'id = 'div4'><h2>FC Porto</h2><a href='https://www.google.com/search?q=fc+porto&oq=fc+porto&aqs=chrome.0.0i271j46i20i131i263i433i512j69i59j0i512l3j69i60j69i61.1205j1j7&sourceid=chrome&ie=UTF-8#sie=t;/m/0177gl;2;/m/03n_lr;mt;fp;1;;'><img src='https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/FC_Porto.svg/180px-FC_Porto.svg.png' id='Leaguelogo'></a><p id='Leaguetext'><b>FC Porto: One of the most dominant clubs in Portugal, FC Porto currently plays in the UEFA Europa League and the Portuguese Primeira Liga. </b><br> Skill Level: High<br> Country: 🇵🇹 <br>Year Founded: 1893<br> Notable Player: Mehdi Taremi</p></div>";
  document.getElementById("div5").outerHTML = "<div id = 'div5' hidden>";
}

function showLeagues() {
  document.getElementById("overview").outerHTML = "<div class='w3-container w3-light-gray' id = 'overview'><h2>Overview</h2><p>This is an online web portal for finding soccer scores pertaining to various leagues. Click the icon of the league you would like to see scores from, or click the <b>Team Portal</b> link above to view teams instead of leagues. The scores are powered by Google.</p></div>";
  document.getElementById("div0").outerHTML = "<div class = 'League' id = 'div0'><h2>UEFA Champions League</h2><a href='https://www.google.com/search?channel=fs&client=ubuntu&q=champions+league#sie=lg;/g/11j8x175ph;2;/m/0c1q0;mt;fp;1;;'><img src='https://upload.wikimedia.org/wikipedia/en/thumb/b/bf/UEFA_Champions_League_logo_2.svg/800px-UEFA_Champions_League_logo_2.svg.png' id='Leaguelogo'></a><p id='Leaguetext'><b>UEFA Champions League:  The League Where Top-Ranked European Clubs Face Off </b> <br>Skill Level: World Class<br> Country: 🇪🇺</p></div>";
  document.getElementById("div1").outerHTML = "<div class = 'League' id = 'div1'> <h2>UEFA Europa League</h2><a href='https://www.google.com/search?q=eufa+europa+league&oq=eufa+europa+league&aqs=chrome..69i57j0i10i131i355i433j0i10i131i433j0i10j0i10i131i433l4j46i10i131i433j0i10.5334j1j4&sourceid=chrome&ie=UTF-8#sie=lg;/g/11hf89b9b3;2;/m/01hrtp;mt;fp;1;;'><img src='https://upload.wikimedia.org/wikipedia/en/thumb/7/77/UEFA_Europa_League_%28football_competition%29_logo.svg/169px-UEFA_Europa_League_%28football_competition%29_logo.svg.png' id='Leaguelogo'></a><p id='Leaguetext'><b>UEFA Europa League:  The second-tier competition of European club football, ranking below the UEFA Champions League</b><br> Skill Level: High<br> Country: 🇪🇺</p></div>";
  document.getElementById("div2").outerHTML = "<div class = 'League' id = 'div2'><h2>English Premier League</h2><a href='https://www.google.com/search?q=Premier+League&client=ubuntu&hs=uRu&channel=fs&sxsrf=APq-WBscoIds197smyJKrRjzExQEYwTxoA%3A1646413041536&ei=8UQiYqXWH8Ga_Qadx6vwCA&ved=0ahUKEwjlkvnD9qz2AhVBTd8KHZ3jCo4Q4dUDCA4&uact=5&oq=Premier+League&gs_lcp=Cgdnd3Mtd2l6EAMyCgguELEDEIMBEEMyBAgAEEMyBwgAELEDEEMyBwgAELEDEEMyBAgAEEMyCAgAEIAEELEDMggIABCABBCxAzIKCAAQsQMQgwEQQzIHCAAQsQMQQzIHCC4Q1AIQQzoHCCMQsAMQJzoHCAAQRxCwAzoHCAAQsAMQQzoKCAAQ5AIQsAMYADoPCC4Q1AIQyAMQsAMQQxgBOgwILhDIAxCwAxBDGAE6BAgjECc6BAguEEM6BQguEIAEOgUIABCABDoOCC4QgAQQsQMQxwEQ0QNKBAhBGABKBAhGGAFQnARYoxFgyRJoAXABeACAAXKIAYUKkgEEMTAuNJgBAKABAcgBE8ABAdoBBggAEAEYCdoBBggBEAEYCA&sclient=gws-wiz#sie=lg;/g/11p44qhs93;2;/m/02_tc;mt;fp;1;;'><img src='https://a.espncdn.com/combiner/i?img=/i/leaguelogos/soccer/500/23.png' id='Leaguelogo'></a><p id='Leaguetext'><b>English Premier League: England's Top League</b><br> Skill Level: High<br> Country: 🏴󠁧󠁢󠁥󠁮󠁧󠁿</p></div>";
  document.getElementById("div3").outerHTML = "<div class = 'League' id = 'div3'><h2>La Liga</h2><a href='https://www.google.com/search?channel=fs&client=ubuntu&q=la+liga#sie=lg;/g/11mqlmppsd;2;/m/09gqx;mt;fp;1;;'><img src='https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/LaLiga_Santander_logo_%28stacked%29.svg/1200px-LaLiga_Santander_logo_%28stacked%29.svg.png' id='Leaguelogo'></a><p id='Leaguetext'><b>La Liga Santander:  The Premier Spanish League</b> <br> Skill Level: High<br> Country: 🇪🇸</p></div>";
  document.getElementById("div4").outerHTML = "<div class = 'League' id = 'div4'> <h2>Primeira Liga</h2><a href='https://www.google.com/search?q=Primiera+Liga&oq=Primiera+Liga&aqs=chrome..69i57j46i10i131i433j0i10i433j0i10l6.887j0j4&sourceid=chrome&ie=UTF-8#sie=lg;/g/11r9859cpq;2;/m/03n_lr;mt;fp;1;;'><img src='https://upload.wikimedia.org/wikipedia/commons/9/9b/S%C3%ADmbolo_da_Liga_Portugal_bwin.png' id='Leaguelogo'></a><p id='Leaguetext'><b>Primeira Liga: The Premier Portuguese League</b><br> Skill Level: Moderate-to-High<br> Country: 🇵🇹</p></div>";
  document.getElementById("div5").outerHTML ="<div class = 'League' id = 'div5'> <h2>MLS</h2><a href='https://www.google.com/search?q=mls&client=ubuntu&hs=rlZ&channel=fs&sxsrf=APq-WBslTe8drz5L1Fa0VSv56UOXg5oB5Q%3A1646412995401&ei=w0QiYrDgF8K5ggex9r-oDw&ved=0ahUKEwjwzfmt9qz2AhXCnOAKHTH7D_UQ4dUDCA4&uact=5&oq=mls&gs_lcp=Cgdnd3Mtd2l6EAMyCgguELEDEIMBEEMyBQgAEIAEMgQIABBDMggIABCABBCxAzIICAAQgAQQsQMyBQgAEIAEMgsIABCABBCxAxCDATIRCC4QgAQQsQMQgwEQxwEQrwEyBQgAEIAEMgQIABBDOgcIABBHELADOgcIABCwAxBDOgoIABDkAhCwAxgAOgwILhDIAxCwAxBDGAE6DwguENQCEMgDELADEEMYAToECCMQJzoHCC4Q1AIQQzoECC4QQzoFCC4QgAQ6CwguELEDEIMBENQCOggILhCxAxCDAUoECEEYAEoECEYYAVDcA1icBWDaBmgBcAF4AIABYogBwgGSAQEymAEAoAEByAEQwAEB2gEGCAAQARgJ2gEGCAEQARgI&sclient=gws-wiz#sie=lg;/g/11s18trfnm;2;/m/0jfpf;mt;fp;1;;'><img src='https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/MLS_crest_logo_RGB_gradient.svg/1200px-MLS_crest_logo_RGB_gradient.svg.png' id='Leaguelogo'></a><p id='Leaguetext'><b>Major League Soccer:  The Premier American League</b><br> Skill Level: Moderate<br> Country: 🇺🇸</p></div>";
}
